baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'PATh'

google_analytics_id: G-0CCSDQV212
homepage:
  show_alert: true
  show_call_box: true
logo:
  mobile: "images/logo/logo.png"
  desktop: "images/logo/logo.png"
  desktop_height: "46px"
footer:
  copyright_text: 'This project is supported by National Science Foundation under Cooperative Agreement OAC-2030508. Any opinions, findings, conclusions or recommendations expressed in this material are those of the authors and do not necessarily reflect the views of the National Science Foundation.'

seo:
  meta_og_title: "Partnership to Advance Throughput Computing"
  meta_og_type: "website"
  meta_og_url: "https://path-cc.io"
  meta_og_description: "PATh brings together the Center for High Throughput Computing and the OSG in order to advance the nationâ€™s campuses and science communities through the use of distributed High Throughput Computing."
  meta_og_image: "https://path-cc.io/images/logo/logo-og.png"
  meta_twitter_card: "summary"
  meta_twitter_site: "PATh"
  meta_twitter_image: "https://path-cc.io/images/logo/logo-twitter.png"

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/
  news:
    output: true
    permalink: /news/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      type: news
    values:
      layout: news
      bodyClass: page-news-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
