name: Check Links
on: pull_request

jobs:
  Check-Website-Links:
    runs-on: ubuntu-18.04

    steps:
      - uses: CannonLock/test_links@master
        with:
          url_ignore: "/https://www.olcf.ornl.gov/summit//,/https://www.hpcwire.com/2019/11/22/51000-cloud-gpus-converge-to-power-neutrino-discovery-at-the-south-pole//,/https://pacificresearchplatform.org//,/https://www.to.infn.it//,/https://www.amnh.org/research/,/https://pace.gatech.edu//,/https://www.amnh.org/research/computational-sciences/,/https://www.amnh.org//,/https://doi.org/10.1007/s10822-013-9672-4/,/https://numerique.banq.qc.ca/rechercheExterne/encoded/Kg==/false/D/asc/W3sibm9tIjoiY29ycHVzIiwidmFsZXVyIjoiUGF0cmltb2luZSUyMHF1w6liw6ljb2lzIn0seyJub20iOiJ0eXBlX2RvY19mIiwidmFsZXVyIjoiUmV2dWVzJTIwZXQlMjBqb3VybmF1eCJ9LHsibm9tIjoiYXZlY190ZXh0ZV9pbnRlZ3JhbCIsInZhbGV1ciI6Im5vbiJ9LHsibm9tIjoiZ2VucmVfZiIsInZhbGV1ciI6IkpvdXJuYXV4In1d/Liste%20de%20r%C3%A9sultats/true/false//,/https://tbg.senckenberg.de//,/https://www.amnh.org/research/staff-directory/ariadna-morales/"

